# Generated by Django 5.2.8 on 2026-01-02 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('is_complete', models.BooleanField(default=False)),
                ('time_start', models.TimeField(auto_now=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(to='characterapp.character')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_complete', models.BooleanField(default=False)),
                ('time_start', models.TimeField(auto_now=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='encounters', to='characterapp.character')),
                ('enemies', models.ManyToManyField(blank=True, related_name='encounters_enemy', to='characterapp.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.game')),
            ],
        ),
    ]
