# Generated by Django 5.2.8 on 2026-01-02 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
        ('game', '0002_game_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'verbose_name': 'Битва', 'verbose_name_plural': 'Битвы'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='encounter',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='encounters', to='characterapp.character', verbose_name='Персонажи'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='enemies',
            field=models.ManyToManyField(blank=True, related_name='encounters_enemy', to='characterapp.character', verbose_name='Враги'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='stage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ход'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='time_start',
            field=models.TimeField(auto_now=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(to='characterapp.character', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.TimeField(auto_now=True, verbose_name='Время начала'),
        ),
    ]
