# Generated by Django 5.2.8 on 2026-01-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_encounter_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
    ]
