# Generated by Django 5.2.8 on 2026-01-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
        ('game', '0004_alter_encounter_time_end_alter_encounter_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(related_name='games', to='characterapp.character', verbose_name='Игроки'),
        ),
    ]
