# Generated by Django 5.2.8 on 2026-01-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
        ('game', '0006_remove_encounter_characters_remove_encounter_enemies'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enemy', models.BooleanField(default=False, verbose_name='Противник')),
                ('initiative', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characterapp.character', verbose_name='Персонаж')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_characters', to='game.encounter', verbose_name='Бой')),
            ],
            options={
                'verbose_name': 'Участник битвы',
                'verbose_name_plural': 'Участники битвы',
            },
        ),
    ]
