# Generated by Django 5.2.8 on 2026-01-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
        ('game', '0007_encountercharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountercharacter',
            name='is_my_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='encountercharacter',
            unique_together={('character', 'encounter')},
        ),
    ]
