# Generated by Django 5.2.8 on 2026-01-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_encountercharacter_is_my_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='Начат'),
        ),
    ]
