# Generated by Django 5.2.8 on 2026-01-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
        ('game', '0009_encounter_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountercharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='characterapp.character', verbose_name='Персонаж'),
        ),
    ]
