# Generated by Django 5.2.8 on 2026-01-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_encountercharacter_character'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encountercharacter',
            unique_together=set(),
        ),
    ]
