# Generated by Django 5.2.8 on 2026-01-06 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_encountercharacter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountercharacter',
            name='hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='encountercharacter',
            name='max_hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
