# Generated by Django 6.0.3 on 2026-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0013_alter_ability_character_alter_skill_ability'),
        ('game', '0012_encountercharacter_hp_encountercharacter_max_hp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['is_complete', '-time_start'], 'verbose_name': 'Битва', 'verbose_name_plural': 'Битвы'},
        ),
        migrations.AlterField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='games', to='characterapp.character', verbose_name='Игроки'),
        ),
    ]
