# Generated by Django 5.2.8 on 2025-11-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('max_hp', models.IntegerField(default=0, verbose_name='Max hp')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('armor_class', models.IntegerField(default=0, verbose_name='КД')),
                ('initiative', models.IntegerField(null=True, verbose_name='Инициатива')),
                ('cooper_coins', models.IntegerField(default=0, verbose_name='ММ')),
                ('silver_coins', models.IntegerField(default=0, verbose_name='СМ')),
                ('gold_coins', models.IntegerField(default=0, verbose_name='ЗМ')),
                ('is_player', models.BooleanField(verbose_name='Игрок')),
                ('player_name', models.CharField(max_length=100, null=True, verbose_name='Имя игрока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Изображение')),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookdata.background', verbose_name='Предыстория')),
                ('dnd_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookdata.dndclass', verbose_name='Класс')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookdata.race', verbose_name='Раса')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Телосложение'), ('INT', 'Интелект'), ('WIS', 'Мудрость'), ('CHR', 'Харизма')], max_length=3, verbose_name='Навык')),
                ('value', models.IntegerField(default=0, verbose_name='Характеристика')),
                ('is_proficient', models.BooleanField(verbose_name='Профильное')),
                ('saving_throw', models.IntegerField(default=0, verbose_name='Спас бросок')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characterapp.character', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'unique_together': {('character', 'ability')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('ATH', 'Атлетика'), ('ACR', 'Акробатика'), ('SOH', 'Ловкость рук'), ('STL', 'Скрытность'), ('ARC', 'Магия'), ('HIS', 'История'), ('INV', 'Анализ'), ('NAT', 'Природа'), ('REL', 'Религия'), ('ANH', 'Уход за животными'), ('INS', 'Проницательность'), ('MED', 'Медицина'), ('PER', 'Восприятие'), ('SUR', 'Выживание'), ('DEC', 'Обман'), ('IND', 'Запугивание'), ('PRF', 'Выступление'), ('PRS', 'Убеждение')], max_length=3, verbose_name='Скилл')),
                ('value', models.IntegerField(default=0, verbose_name='Характеристика')),
                ('is_proficient', models.BooleanField(verbose_name='Профильное')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characterapp.ability', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
                'unique_together': {('ability', 'skill')},
            },
        ),
    ]
