# Generated by Django 5.2.8 on 2025-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0002_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='is_proficient',
            field=models.BooleanField(default=False, verbose_name='Профильное'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_proficient',
            field=models.BooleanField(default=False, verbose_name='Профильное'),
        ),
    ]
