# Generated by Django 5.2.8 on 2025-11-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0003_alter_ability_is_proficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilities', to='characterapp.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='characterapp.ability', verbose_name='Навык'),
        ),
    ]
