# Generated by Django 5.2.8 on 2025-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0004_alter_ability_character_alter_skill_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
