# Generated by Django 5.2.8 on 2025-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0005_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dnd_subclass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подкласс'),
        ),
    ]
