# Generated by Django 5.2.8 on 2025-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0006_character_dnd_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя игрока'),
        ),
    ]
