# Generated by Django 5.2.8 on 2025-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0007_alter_character_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficient_bonus',
            field=models.IntegerField(default=2, verbose_name='Бонус мастерства'),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Скорость'),
        ),
    ]
