# Generated by Django 5.2.8 on 2025-11-23 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0008_character_proficient_bonus_character_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Телосложение'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHR', 'Харизма')], max_length=3, verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='КД'),
        ),
        migrations.AlterField(
            model_name='character',
            name='cooper_coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ММ'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold_coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ЗМ'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max hp'),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver_coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='СМ'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скорость'),
        ),
    ]
