# Generated by Django 5.2.8 on 2025-12-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0009_alter_ability_ability_alter_character_armor_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
