# Generated by Django 5.2.8 on 2025-12-05 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0002_alter_background_options_alter_dndclass_options_and_more'),
        ('characterapp', '0010_character_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('name', 'race', 'user')},
        ),
    ]
