# Generated by Django 5.2.8 on 2026-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0011_alter_character_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=0, null=True, verbose_name='Инициатива'),
        ),
    ]
