# Generated by Django 5.2.8 on 2026-02-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0012_alter_character_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='characterapp.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characterapp.ability', verbose_name='Навык'),
        ),
    ]
