# Generated by Django 5.2.8 on 2025-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name': 'Происхождение', 'verbose_name_plural': 'Происхождения'},
        ),
        migrations.AlterModelOptions(
            name='dndclass',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Раса', 'verbose_name_plural': 'Расы'},
        ),
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookdata/backgrounds/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dndclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookdata/classes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dndclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookdata/races/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
